int changeprize(int);
void reservation(int *,int,int );
int choice1(void);
void cancel(int *);     
int cmovie(void);
int movie(void);
void details(void);   
void ticket1(int choice,char name[10],int id2,int price);
void ticket2(int choice,char name[10],int id2,int price);
void ticket3(int choice,char name[10],int id2,int price);
